server:
    servlet:
        encoding:
            force-response: 'true'
    port: '8088'
spring:
    devtools:
        livereload:
            enabled: true
    jpa:
        defer-datasource-initialization: 'true'
        show-sql: 'true'
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                '[format_sql]': 'true'
    datasource:
        password: 'admin'
        driver-class-name: com.mysql.cj.jdbc.Driver
        generate-unique-name: 'false'
        username: admin
        url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    sql:
        init:
            mode: never
            encoding: UTF-8
    data:
        web:
            pageable:
                default-page-size: 10
                page-parameter: p
                # one-indexed-parameters: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
                SQL: DEBUG
# news:
#   imgdir: D:/SpringTest/news/src/main/resources/static/img/

